/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/fabrik3d.py
 *
 * Regenerate:   python -m ramulator codegen Fabrik3D
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFpb.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class Fabrik3D : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREpb, PREab, RD, WR, RDA, WRA, REFpb, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nCWL,
      nRCD,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCCD,
      nRRD,
      nRTW,
      nWTR,
      nPPD,
      nRFCpb,
      nREFIpb,
      tCK_ps,
      COUNT
    };
  };

  using CommandImpls = std::tuple<Cmd::ACT<Fabrik3D>, Cmd::PREpb<Fabrik3D>, Cmd::PREab<Fabrik3D>, Cmd::RD<Fabrik3D>,
                                  Cmd::WR<Fabrik3D>, Cmd::RDA<Fabrik3D>, Cmd::WRA<Fabrik3D>, Cmd::REFpb<Fabrik3D> >;

  Fabrik3D(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Bank", "Row", "Column"});
    set_names(commands, command_names, {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFpb"});
    set_names(states, state_names, {"Opened", "Closed", "N_A"});
    set_names(timings, timing_names,
              {"rate", "nBL", "nCL", "nCWL", "nRCD", "nRP", "nRAS", "nRC", "nWR", "nRTP", "nCCD", "nRRD", "nRTW",
               "nWTR", "nPPD", "nRFCpb", "nREFIpb", "tCK_ps"});

    // Static spec data
    internal_prefetch_size = 1;
    init_states = {
        State::N_A,     // Channel
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,  // Read -> RD
        Command::WR,  // Write -> WR
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_fabrik3d = DRAMSpec::register_standard(
    "Fabrik3D", [](const ConfigNode& config) { return std::make_unique<Fabrik3D>(config); });

}  // namespace Ramulator
